=== kyo19/easy-java-validation/easy-validation/src/main/resources/easy-validation.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
-->
<!ELEMENT validations (properties*, validation+)>
<!ATTLIST validations>
  
<!ELEMENT properties (file+)>
<!ATTLIST properties locale (US|FR|EN|SA|CN|TW|NL|AU|CA|GB|DE|IL|IN|IT|JP|KR|BR|ES|SE|TH) #REQUIRED>

<!ELEMENT file (#PCDATA)>
<!ATTLIST file >

<!ELEMENT validation (rule)+>
<!ATTLIST validation name NMTOKEN #REQUIRED>

<!ELEMENT rule (param?,message)>
<!ATTLIST rule 
  fieldName NMTOKEN #IMPLIED
  type (required|int|double|email|expression|date|stringlength|url) #REQUIRED>

<!ELEMENT param EMPTY>
<!ATTLIST param
  dateformat NMTOKEN #IMPLIED
  expression CDATA #IMPLIED
  max NMTOKEN #IMPLIED
  min NMTOKEN #IMPLIED
  regex (true|false) "false">

<!ELEMENT message (#PCDATA)>
<!ATTLIST message
  key NMTOKEN #IMPLIED
  useAttributePlaceHolder (true|false) "false">

=== kyo19/easy-java-validation/tags/2.0/easy-validation-showcase/WEB-INF/src/applicationValidations.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE validations SYSTEM "easy-validation.dtd">

<validations>

	<properties locale="EN">
		<file>error_message_en.properties</file>
	</properties>
	
	<validation name="userFormValidation">
		<rule type="required" fieldName="name">
			<message key="name.required"/>
		</rule>
		
		<rule type="stringlength" fieldName="name">
			<param min="5" max="10"/>
			<message useAttributePlaceHolder="true">${fieldName} should be between ${min} and ${max}</message>
		</rule>
		
		<rule type="email" fieldName="email">
			<message>Email is not in proper format</message>
		</rule>
		
		<rule type="expression" fieldName="zipcode">
			<param expression="^\d{5}([\-]\d{4})?$" regex="true"/>
			<message>Zipcode should be of length 4 or 5</message>
		</rule>
		
		<rule type="expression">
			<param expression="#age > 21"/>
			<message>Age should be above 21</message>
		</rule>
		
		<rule type="url" fieldName="url">
			<message>URL is not in proper format</message>
		</rule>
		
		<rule type="date" fieldName="dob">
			<param max="currentDate" dateformat="dd/MM/yyyy"/>
			<message>Date of birth should not be greater than today</message>
		</rule>
		
		<rule type="creditcard" fieldName="creditcardNo">
			<message>Credit Card number is not in proper format</message>
		</rule>
		
		<rule type="isbn" fieldName="isbn">
			<message>ISBN is not in proper format</message>
		</rule>
		
		<rule type="inetaddress" fieldName="inetaddress">
			<message>IP Address is not in proper format</message>
		</rule>
	</validation>
</validations>
